# ---------------------------------------------------------
# Grafana (with provisioning + default dashboard)
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.0.0
        ports:
          - containerPort: 3000
        env:
          - name: GF_SECURITY_ADMIN_USER
            value: admin
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: admin
        volumeMounts:
          - name: grafana-provisioning
            mountPath: /etc/grafana/provisioning
          - name: grafana-dashboards
            mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: elk
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Elasticsearch
        type: elasticsearch
        access: proxy
        url: http://elasticsearch:9200
        isDefault: true
        jsonData:
          timeField: "@timestamp"

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: elk
data:
  metrics-dashboard.json: |
    {
      "id": null,
      "uid": "per-second-metrics",
      "title": "Per Second Metrics",
      "timezone": "browser",
      "schemaVersion": 36,
      "version": 1,
      "refresh": "1s",
      "panels": [
        {
          "type": "timeseries",
          "title": "Live Metrics per Second",
          "targets": [
            {
              "refId": "A",
              "datasource": {
                "type": "elasticsearch",
                "uid": "-100"
              },
              "timeField": "@timestamp",
              "metrics": [
                { "id": "1", "type": "avg", "field": "metric" }
              ],
              "bucketAggs": [
                {
                  "type": "date_histogram",
                  "id": "2",
                  "field": "@timestamp",
                  "settings": {
                    "interval": "1s",
                    "min_doc_count": 1
                  }
                }
              ]
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "none",
              "color": {
                "mode": "palette-classic"
              }
            },
            "overrides": []
          },
          "options": {
            "legend": {
              "displayMode": "table",
              "placement": "bottom"
            }
          },
          "gridPos": {
            "h": 12,
            "w": 24,
            "x": 0,
            "y": 0
          }
        }
      ],
      "time": {
        "from": "now-5m",
        "to": "now"
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: elk
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
