apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-generator
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-generator
  template:
    metadata:
      labels:
        app: metrics-generator
    spec:
      containers:
      - name: metrics-generator
        image: python:3.9-slim
        command: ["sh", "-c"]
        args:
          - |
            pip install requests && python - <<'PY'
            import time, json, random, datetime, requests

            LOGSTASH_URL = "http://logstash:5044"

            while True:
                doc = {
                    "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
                    "metric_name": "cpu_usage",
                    "value": random.uniform(10.0, 95.0),
                    "host": "local-mac"
                }
                try:
                    requests.post(LOGSTASH_URL, json=doc, timeout=2)
                except Exception as e:
                    print("Error sending metric:", e)
                time.sleep(1)
            PY

