# Metrics Generator 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-generator
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-generator
  template:
    metadata:
      labels:
        app: metrics-generator
    spec:
      containers:
      - name: metrics-generator
        image: curlimages/curl:8.4.0
        command:
          - /bin/sh
          - -c
          - |
            while true; do
              TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ");
              VALUE=$((RANDOM % 100));
              curl -s -XPOST http://logstash:5044 \
                -H "Content-Type: application/json" \
                -d "{\"@timestamp\":\"$TS\", \"metric\":$VALUE}";
              sleep 1;
            done
